// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyConYmVkt7e8DcINZxSBlAMt2GrCtB-6jY',
    appId: '1:304093722137:web:2be0f7b373c35ef7ea9c88',
    messagingSenderId: '304093722137',
    projectId: 'shop-beer',
    authDomain: 'shop-beer.firebaseapp.com',
    databaseURL: 'https://shop-beer-default-rtdb.firebaseio.com',
    storageBucket: 'shop-beer.appspot.com',
    measurementId: 'G-1RMPC3H6PQ',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD8GESHeVYS-yZUm3n9ytoAPIqQkM0xd7E',
    appId: '1:304093722137:android:33a9fcb7741f7b1bea9c88',
    messagingSenderId: '304093722137',
    projectId: 'shop-beer',
    databaseURL: 'https://shop-beer-default-rtdb.firebaseio.com',
    storageBucket: 'shop-beer.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBBLwo8FtYwlBLqLHQLGpqIo2yr8GYljjI',
    appId: '1:304093722137:ios:0e43a3c888e6ea9eea9c88',
    messagingSenderId: '304093722137',
    projectId: 'shop-beer',
    databaseURL: 'https://shop-beer-default-rtdb.firebaseio.com',
    storageBucket: 'shop-beer.appspot.com',
    iosClientId: '304093722137-rm734j1qfpoucrepqckruo9g0cc3l4od.apps.googleusercontent.com',
    iosBundleId: 'com.ggp0.shopbeer',
  );
}
